"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const pizzeria_1 = require("./pizzeria/pizzeria");
const receipts_1 = require("./data/receipts");
const types_1 = require("./data/types");
const pizzeria = new pizzeria_1.Pizzeria("Lisitsa", "Tverskaya st, 24", "10.00 - 24.00");
const order = pizzeria.createOrder();
order.addPizza(receipts_1.PIZZA_NAMES.PEPPERONI, types_1.PIZZA_SIZE.LARGE, receipts_1.pizzaReceipts[receipts_1.PIZZA_NAMES.PEPPERONI].prices[types_1.PIZZA_SIZE.LARGE], receipts_1.pizzaReceipts[receipts_1.PIZZA_NAMES.PEPPERONI].toppings, types_1.DOUGH_TYPE.FERMENTED);
order.addPizza(receipts_1.PIZZA_NAMES.HAWAII, types_1.PIZZA_SIZE.LARGE, receipts_1.pizzaReceipts[receipts_1.PIZZA_NAMES.HAWAII].prices[types_1.PIZZA_SIZE.LARGE], receipts_1.pizzaReceipts[receipts_1.PIZZA_NAMES.HAWAII].toppings, types_1.DOUGH_TYPE.THICK, ["olives", "mushrooms"]);
console.log(order.getMeals());
console.log(order.getFullPrice());
order.removeFromOrder(receipts_1.PIZZA_NAMES.HAWAII);
